[package]
name = "mirror-metrics"
version = "0.0.1"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0"
chrono = "0.4"
rayon = "1.9"
flate2 = "1.0"
clap = { version = "4.5.1", features = ["derive"] }
